### PR TITLE
categories.ts updated

### LINKED ISSUE #34: Add more filter categories/options to get more precise results
More filters needed for exact and accurate results

### PR DESCRIPTION
**Pull request by sahitya-chandra**
closes #34 
Added some more categories for more smooth user experience

### CODE REVIEW

**Comment by dotslashbit** [comment]
@sahitya-chandra will review it tomorrow. One more thing, the new changes are working corectly, right?

**Comment by sahitya-chandra** [comment]
@dotslashbit Yes sir they are working correctly...

**Comment by dotslashbit** [comment]
@sahitya-chandra Awesome, will review it in the morning, thank you so much for your contribution, if you want to add more categories then feel free to do so.

One more thing, whenever you are creating a PR, type this in the description so that the PR gets mapped to the respective issue and the issue will close automatically if the PR gets merged.

Always type this first:

closes #<issue_number>

After you write closes # then you'll see auto complete like you see in any text editor. Please update the description. It'll help you in future contributions be it in this repo or any other repo

**Comment by dotslashbit** [comment]
@sahitya-chandra Thank you so much for your contribution, I really appreciate it 😊

**Pull request merged**
