### PR TITLE
changed GitHub  icon

### LINKED ISSUE #61: Update the Github Icon on the Header
Screenshot 2024-08-30 at 10 22 26

We want the github icon to be similar to what hugo website has.

If you want to work on it, just comment down below

If you got stuck, me and other constributors are here to help, please feel free to reach out to anyone

### PR DESCRIPTION
**Pull request by enriqueqs**
closes #61 
changed github Icon  to look like the one in the Hugo website 

output1

### CODE REVIEW

**Comment by dotslashbit** [comment]
@enriqueqs Hi, thank you so much for your contribution. It means a lot.

Can you send a screen recording of the update 

One more thing in your description of this Pr, on the very top write like this:

closes #<issue_number>

Keep space between closes and #

**Comment by dotslashbit** [comment]
@enriqueqs make sure it opens up in a new tab

**Comment by enriqueqs** [comment]
> @enriqueqs Hi, thank you so much for your contribution. It means a lot.
> 
> Can you send a screen recording of the update
> 
> One more thing in your description of this Pr, on the very top write like this:
> 
> closes #<issue_number>
> 
> Keep space between closes and #

done


> @enriqueqs make sure it opens up in a new tab

done as well

**Comment by dotslashbit** [comment]
@enriqueqs Sorry to bother you, but can you align the icon correctly. Currently its a bit above the center

**Comment by enriqueqs** [comment]
@dotslashbit just fixed the alignment
Screenshot 2024-08-30 at 12 57 49

**Review by dotslashbit — APPROVED** [review]

**Comment by dotslashbit** [comment]
@enriqueqs Thank you so much for your contribution, this is very impactful contribution 🎉

**Pull request merged**
