### PR TITLE
Fix: Change Footer layout

### LINKED ISSUE #70: Update Footer text position
Screenshot 2024-09-01 at 20 33 57

Keep everything centered.
Put the texts from left to the center.
Then below these texts put the icons

If you want to contribute, please comment down below.
If you get stuck, then please reach out to me or any contributors, we are here to help 😊

### PR DESCRIPTION
**Pull request by rodriveiga01**
# Summary

This pull request has changes based on issue #70 , that is about changing layout of Footer

# Changes
- Changed Footer to be column even on desktop so the text is on top of the icons. Icons are below of text but with the right padding
- It's all centered and responsive for desktop, tablet and mobile
- Updated package-lock to remove vulnerabilities. The website works like normal
- Remove .husky first two lines in pre-commit file because of warning when testing the website. The website works like normal

## Image
New Footer

# Resolved Issues

Resolves #70

### CODE REVIEW

**Comment by omjogani** [comment]
@rodriveiga01 Would you mind sharing a screenshot of the warning you're getting without removing first 2 lines in `.husky`?

**Comment by omjogani** [comment]
@rodriveiga01 Please also mention, what vulnerabilities you found that led you to modify `package.lock` file?

**Comment by dotslashbit** [comment]
@omjogani thanks for checking this out, let me know when everything is done, I'll merge it

**Comment by rodriveiga01** [comment]
Because it found some warnings of vulnerabilities and install command is deprecated, I used the "npm update" and it updated everything and it then didn't have warnings and it worked like normal

Captura de ecrã 2024-09-02, às 10 13 10

**Comment by rodriveiga01** [comment]
The warning from husky was this:
```
Please remove the following lines from ./.husky/pre-commit:

#!/usr/bin/env sh
. \"\$(dirname -- \"\$0\")/_/husky.sh\"

They WILL FAIL in v10.0.0
```
Captura de ecrã 2024-09-02, às 10 19 48
This appears in the release of the version 9.0.1 which says that the two lines can and need to be removed

**Comment by rodriveiga01** [comment]
Also when I ran "npm run dev" it would show me an error before updating the package.lock:
Captura de ecrã 2024-09-02, às 10 54 33

After I ran npm update it would work

**Comment by rodriveiga01** [comment]
If all of you agree I think it would be goo to change the `README.md` because there it says to run "npm install" but that command is deprecated. It would be needed to change to "npm update"

**Comment by dotslashbit** [comment]
@omjogani Please check this, thanks

**Comment by omjogani** [comment]
@rodriveiga01 Here is what's going on!

When I configured Husky, It was working well and then There was migration from Husky which was leading to the state that "install is DEPRECATED".  but the issue is we haven't migrated the configuration to the latest one. There is no requirement of updating dependencies in my opinion.

You don't really have to run `npm update` command, just follow below step

1. Take out changes you've done in the project apart from configuration (FooterFile)
2. Reset this branch to main branch
3. Remove those 2 line in `.husky` file, New content will be
```bash
npx lint-staged
```
4. In `package.json` file, in the script update `prepare` script
Old: `"prepare": "husky install"`
New: `"prepare": "husky"`
5. Add your changes (Footer file)
6. Test out everything is working
7. push it again

**Comment by omjogani** [comment]
Migration Guide: https://github.com/typicode/husky/releases/tag/v9.0.1

Let me know if you need any help! @rodriveiga01

**Comment by rodriveiga01** [comment]
@omjogani Thanks a lot for the instructions. Its all working as expected

**Comment by rodriveiga01** [comment]
I did a force push to reset the changes. I don't know if it's the best practice but was what I knew

**Comment by dotslashbit** [comment]
@rodriveiga01 Thank you so much for your contribution. Let me just get the confirmation from @omjogani and then I'll merge it.

@omjogani Just let us know if its good to go or not, thank you

**Comment by rodriveiga01** [comment]
Ok sounds good

**Review by omjogani — APPROVED** [review]
Looks good to me! Thanks @rodriveiga01 for noticing that!

**Comment by omjogani** [comment]
@dotslashbit Merge this please!

**Pull request merged**
