### PR TITLE
Fix graphql

### LINKED ISSUE #49: Update Github API query
Currently the api query fetches issues with closed PRs only when hasPR is checked. We need to update the query so that it'll fetch:
- All issues without PRs and closed PRs (when hasPR is false)
- All issues with open PRs or draft PRs (when hasPR is true)

If you want to work on this, please comment below. If you need any help, just ping me, I can help you with this, thanks

### PR DESCRIPTION
**Pull request by Sechorda**
Resolves #49

Modified Graphql query and logic to only return:

Issues with HasPRs: False
Issues with HasPRs: True if State is Open, Draft, closed, or NULL.

Some cases showed HasPR: True but state: Null. Manually reviewed and did not see any PRs for the mentioned issue, this could be a github API bug.

### CODE REVIEW

**Comment by Sechorda** [comment]
Tested on my end, Ready for review.

**Comment by dotslashbit** [comment]
@Sechorda I have shared a docs link in the issue, please take a look and let me know what you think?

**Comment by Sechorda** [comment]
Converting to draft to determine best strategy for filtering.

**Comment by dotslashbit** [comment]
@Sechorda Merging this Pr as it seems fine to me, Later when we'll add tests, then we can again see if it actually holds all possible cases or not.

**Review by dotslashbit — APPROVED** [review]

**Pull request merged**
