### PR TITLE
Mobile UI

### LINKED ISSUE #32: Improve Mobile UI
Many people scour the “good first issue” label.

you should add a few random ones to your site maybe here?
IMG_2748

### PR DESCRIPTION
**Pull request by Sechorda**
Resolves #32

### CODE REVIEW

**Comment by Sechorda** [comment]
Need further testing/revision.

**Comment by dotslashbit** [comment]
@Sechorda Thank you so much for your contribution, can you please share a screen recording or a loom video on the changes?

**Comment by Sechorda** [comment]
@dotslashbit Sure, check this out.

[Screen recording 2024-08-26 7.39.46 PM.webm](https://github.com/user-attachments/assets/c1eb777e-9a02-4b5c-9b5f-3cada09ac746)

**Comment by dotslashbit** [comment]
@Sechorda This looks great, I'll merge it as soon as I get to my laptop.

A huge thank you for working on this issue. It was an important one.

There's still a problem, you can see that in the loading phase it says something like no issues found, we need to remove that.

I'll create an issue and tag you, let me know if you want to work on that?

Btw, can you tell me how you got to know about this repo?

**Comment by dotslashbit** [comment]
@Sechorda Hi, its good to go just one more thing, there's a breakpoint before the full screen view and the mobile view, can you implement the new filter UI on that view as well?

**Comment by Sechorda** [comment]
@dotslashbit 

Let me know if these breakpoints are better suited for the app.
Also, check out this new suspense/transition to fix the message that was flashing...

[Screen recording 2024-08-27 8.29.22 AM.webm](https://github.com/user-attachments/assets/4c7e013b-483e-404d-9968-523fa5bbd6cf)

Quick question - Is the .husky directory/tool still being utilized for this project? It looks like it runs a .sh just saying it's deprecated. Also - when checking the developer console in chrome, there's all sorts of remix modules trying to reach out to some other local ports. are these service on the live host, or previous development sockets?

ty

**Comment by dotslashbit** [comment]
@Sechorda just remove the Livereload component from the root.tsx file, then all of the console errors will be removed

we are using the .husky directly for a pre commit command, let it be there

**Comment by Sechorda** [comment]
@dotslashbit Nice! I would like to pick up some more issues this week as they come, or work on perfecting the mobile UI further.

**Comment by dotslashbit** [comment]
Please feel free to pick up new ones (if any otherwise you can create issues and then start working on them)

**Comment by Sechorda** [comment]
@dotslashbit How do you feel about refactoring the project structure, maybe merging the components folders?

**Comment by dotslashbit** [comment]
@Sechorda Actually I would love that but lets do that on a new issue, its best to create different issues for different problems rather than solving all of them at once.

**Pull request closed without merging**
