### PR TITLE
Fix: Prevent user from entering negative and false values in the filter 

### LINKED ISSUE #42: Restrict user from entering Max Stars value less than Min Stars value
I noticed, that the user can enter a Max Star value less than the Min Star value. By this, the user cannot able to see any issues.

image

### PR DESCRIPTION
**Pull request by pamarthiabhinav**
## Description
This update prevents users from entering negative values in the "Min Stars" and "Max Stars" filters. Additionally, it ensures that the "Max Stars" value must always be greater than or equal to the "Min Stars" value.

## Issues Addressed:
- Closes #42

## Screenshots
image
image

### CODE REVIEW

**Comment by dotslashbit** [comment]
@pamarthiabhinav Its ready to be merged, but can you also do this for min forks

**Comment by pamarthiabhinav** [comment]
Done @dotslashbit, Made changes for the Min Stars as well, restricted to enter less than Max Stars

**Comment by dotslashbit** [comment]
That's awesome @pamarthiabhinav Just want you to update it so that no can enter negative values in min, max and fork inputs.
Let me know when its done, I'll merge it right away

**Comment by pamarthiabhinav** [comment]
@dotslashbit Done with the forks as well, you can go ahead and merge it

**Comment by dotslashbit** [comment]
@pamarthiabhinav Awesome

**Comment by dotslashbit** [comment]
@pamarthiabhinav Let me know if you want to work on the mobile Ui stuff? Its actually a important issue.

There's no rush

**Pull request merged**
