### PR TITLE
Feature/multiple languages

### PR DESCRIPTION
**Pull request by ST-KO**
@dotslashbit I have done it. Please review the code for me. Thanks.

### CODE REVIEW

**Comment by dotslashbit** [comment]
@ST-KO Hi, thank you so much for your contribution, can you please add a screen recording on its working

**Comment by ST-KO** [comment]
> @ST-KO Hi, thank you so much for your contribution, can you please add a screen recording on its working

Hi there, sorry for my late reply. Here is the screen recording...

https://github.com/user-attachments/assets/87091b5e-c0bf-4a71-b6d7-8f555f266f28

**Comment by Sechorda** [comment]
resolves #35

**Review by dotslashbit — APPROVED** [review]

**Comment by dotslashbit** [comment]
@ST-KO Thank you so much for your contribution, this has enhanced the user experience by a lot. We are always happy have you as a contributor.

Don't feel sorry about the delay in reply, you and all other contributors (including me) are working on this whenever we can, everyone has other things to do in their life. So, I'll understand even if you can't respond for multiple days.

I'll be happy if you will stay and contribute more, thank you so much

**Pull request merged**
